version: '3.1'

services:
  php:
    build: .
    ports:
      - "8000:80"
      - "1443:443"
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=rede_social

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080